baseURL = "https://snowballons.netlify.app/"
languageCode = "en-us"
title = "John Okeno — Jonnie Brown"
theme = "PaperMod"


[pagination]
  pagerSize = 10

[params]
  # we’ll use these later for toggles (comments/search/etc.)
  disableComments = false
