[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  # set this to match your local `hugo version` (Extended) to avoid build mismatches
  HUGO_VERSION = "YOUR_LOCAL_VERSION"
